server:
  port: 5000

management:
  endpoints:
    web:
      exposure:
        include: mappings,env,beans,conditions

mybatis:
  mapper-locations: classpath:mybatis/*.xml

aws:
  s3:
    bucket-name: resume-backend-app

cloud:
  aws:
    credentials:
      access-key: AKIAULGZ7ETA4R4DECGC
      secret-key: ENC(jMVO9tgRaxUAI+c+jAW0JhwIbimDEuVhi0eOpvSaGBlk+HhigBsmUZUFgEo5CJD2isMSAsFr9CkfFxtFccD/f7AHvQp6h3OIWwkUSURsAsc=)
    region:
      static: ap-northeast-1
      auto: false
    stack:
      auto: false
    s3:
      bucket-name: resume-backend-app

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2MB

jasypt:
  encryptor:
    password: resume